# Usamos una imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para la base de datos
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB database

# Copiamos el archivo SQL de inicialización

