FROM node:18-alpine

RUN mkdir /app

WORKDIR /app

COPY package*.json ./

COPY jsconfig.json ./

COPY yarn.lock ./

RUN yarn install

COPY public ./public

COPY src ./src

EXPOSE 3000

ENTRYPOINT [ "yarn", "dev", "--host", "0.0.0.0", "--port", "3000" ]
