version: "3"
services:
  database:
    image: caso17/database
    ports:
      - "27017:27017"
  server:
    image: caso17/server
    ports:
      - "4000:4000"
    depends_on:
      - database
  client:
    image: caso17/client 
    ports:
      - "8080:8080"
    depends_on:
      - server